import { Language, QuoteCategory } from '../types';

export const QUOTES: Record<Language, Record<QuoteCategory, string[]>> = {
  ja: {
    mementoMori: [
      "終わりを想い、今、この一瞬を愛せ。",
      "メメント・モリ。死を忘れるな、生を輝かせよ。",
      "今日という日は、残りの人生の最初の一日である。",
      "時間は、私たちが最も欲しがるものであるが、最も無駄に使ってしまうものでもある。",
      "明日死ぬかのように生きよ。永遠に生きるかのように学べ。",
      "人生は短い。しかし、微笑む時間はたっぷりある。",
      "一日は一生の短縮版である。",
      "あなたが無駄に過ごした今日は、昨日死んだ誰かが死ぬほど生きたかった明日だ。",
      "今この瞬間、あなたは生きている。それ以上に素晴らしいことはない。",
      "死は人生の終末ではない。生涯の完成である。",
      "生きるとは、呼吸することではない。行動することだ。",
      "最も長生きした人間とは、最も多くの歳月を生きた人間ではなく、最も人生を感じた人間だ。",
      "人生において重要なのは、何年生きたかではない。その歳月の中にどれだけの命があったかだ。",
      "未来は、今、あなたが何をするかにかかっている。",
      "幸福は、明日手に入れるものではない。今日、この瞬間に作り出すものだ。",
      "過去は変えられないが、未来は今から作ることができる。",
      "一瞬一瞬が、新しい始まりだ。",
      "人生の価値は、その長さではなく、その使い方で決まる。",
      "死を意識することは、生を豊かにすることだ。",
      "今日、あなたができる最善を尽くせ。"
    ],
    stoicism: [
      "君の力でどうにもならないことに、心を煩わせるな。（エピクテトス）",
      "幸福への道はただ一つ。自分の力ではどうにもならないことを悩むのをやめることだ。（エピクテトス）",
      "運命は志ある者を導き、志なき者を引きずっていく。（セネカ）",
      "私たちが持っている時間は短いのではなく、私たちが多くを浪費しているのだ。（セネカ）",
      "最高の復讐は、自分を傷つけた相手のようにならないことだ。（マルクス・アウレリウス）",
      "朝起きたらこう考えよ。今日、私は、おせっかいな人間、恩知らずな人間、傲慢な人間、不正直な人間、嫉妬深い人間、非社会的な人間に会うだろう、と。（マルクス・アウレリウス）",
      "人生は戦いであり、異郷の旅である。（マルクス・アウレリウス）",
      "困難が大きければ大きいほど、それを克服した時の栄光も大きい。（エピクテトス）",
      "人間を不安にさせるのは、事柄そのものではなく、その事柄に関する意見である。（エピクテトス）",
      "今この瞬間に集中せよ。それが君にできる唯一のことだ。"
    ],
    zen: [
      "日々世好日（にちにちこれこうじつ）。",
      "前後際断（ぜんごさいだん）。過去にも未来にもとらわれず、今を生きよ。",
      "柳は緑、花は紅。あるがままの姿を受け入れよ。",
      "一期一会。この出会いは二度とない。",
      "柔軟心（にゅうなんしん）。何事にもとらわれない、しなやかな心を持て。",
      "知足（ちそく）。足るを知る者は富む。",
      "歩歩は道場（ほほこれどうじょう）。一歩一歩の歩みそのものが修行である。",
      "本来無一物（ほんらいむいちもつ）。執着を捨てれば、心は自由になる。",
      "看脚下（かんきゃか）。足元を見よ。今、自分がどこにいるかを確認せよ。",
      "冷暖自知（れいだんじち）。水が冷たいか温かいかは、飲んでみなければわからない。"
    ],
    entrepreneur: [
      "ハングリーであれ、愚かであれ。（スティーブ・ジョブズ）",
      "あなたの時間は限られている。だから、誰か他の人の人生を生きて無駄にしてはいけない。（スティーブ・ジョブズ）",
      "失敗は、より賢明に再挑戦するための機会に過ぎない。（ヘンリー・フォード）",
      "成功を祝うのはいいが、もっと大切なのは失敗から学ぶことだ。（ビル・ゲイツ）",
      "最大のリスクは、リスクを全く取らないことだ。（マーク・ザッカーバーグ）",
      "情熱を持って取り組めることを見つけなさい。そうでなければ、続けることはできない。（ジェフ・ベゾス）",
      "成功とは、情熱を失わずに、失敗から失敗へと突き進む能力のことだ。（ウィンストン・チャーチル）",
      "夢を見ることができるなら、それは実現できる。（ウォルト・ディズニー）",
      "行動こそが、すべての成功の鍵である。（パブロ・ピカソ）",
      "今から20年後、あなたは「やったこと」よりも「やらなかったこと」に失望するだろう。（マーク・トウェイン）"
    ]
  },
  en: {
    mementoMori: [
      "Remember that you must die. Love this moment now.",
      "Memento Mori. Do not forget death, let life shine.",
      "Today is the first day of the rest of your life.",
      "Time is what we want most, but what we use worst.",
      "Live as if you were to die tomorrow. Learn as if you were to live forever.",
      "Life is short, but there is plenty of time to smile.",
      "A day is a miniature of eternity.",
      "The today you wasted is the tomorrow someone who died yesterday wanted to live.",
      "At this moment, you are alive. Nothing is more wonderful than that.",
      "Death is not the end of life; it is the completion of a lifetime.",
      "To live is not just to breathe, but to act.",
      "The man who has lived the most is not he who has counted the most years but he who has most felt life.",
      "In the end, it's not the years in your life that count. It's the life in your years.",
      "The future depends on what you do today.",
      "Happiness is not something you postpone for the future; it is something you design for the present.",
      "You cannot change the past, but you can create the future starting now.",
      "Every moment is a fresh beginning.",
      "The value of life lies not in the length of days, but in the use we make of them.",
      "Being aware of death is to enrich life.",
      "Do your best today."
    ],
    stoicism: [
      "Don't explain your philosophy. Embody it. (Epictetus)",
      "We suffer more often in imagination than in reality. (Seneca)",
      "The best revenge is to be unlike him who performed the injury. (Marcus Aurelius)",
      "It is not death that a man should fear, but he should fear never beginning to live. (Marcus Aurelius)",
      "You have power over your mind - not outside events. Realize this, and you will find strength. (Marcus Aurelius)",
      "Luck is what happens when preparation meets opportunity. (Seneca)",
      "He who is brave is free. (Seneca)",
      "Waste no more time arguing what a good man should be. Be one. (Marcus Aurelius)",
      "If it is not right, do not do it; if it is not true, do not say it. (Marcus Aurelius)",
      "Difficulties strengthen the mind, as labor does the body. (Seneca)"
    ],
    zen: [
      "Every day is a good day.",
      "Be here now.",
      "When you are hungry, eat; when you are tired, sleep.",
      "The obstacle is the path.",
      "Chop wood, carry water.",
      "Smile, breathe and go slowly.",
      "The only way to do great work is to love what you do.",
      "Do not seek to follow in the footsteps of the men of old; seek what they sought.",
      "Zen is not some kind of excitement, but concentration on our usual everyday routine.",
      "Everything is changing; nothing is permanent."
    ],
    entrepreneur: [
      "Stay hungry, stay foolish. (Steve Jobs)",
      "Your time is limited, so don't waste it living someone else's life. (Steve Jobs)",
      "Failure is simply the opportunity to begin again, this time more intelligently. (Henry Ford)",
      "It's fine to celebrate success but it is more important to heed the lessons of failure. (Bill Gates)",
      "The biggest risk is not taking any risk. (Mark Zuckerberg)",
      "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward. (Martin Luther King Jr.)",
      "Success is walking from failure to failure with no loss of enthusiasm. (Winston Churchill)",
      "If you can dream it, you can do it. (Walt Disney)",
      "Action is the foundational key to all success. (Pablo Picasso)",
      "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. (Mark Twain)"
    ]
  },
  zh: {
    mementoMori: [
      "记住你终将逝去，爱在当下。",
      "记住死亡，让生命闪耀。",
      "今天是你余生的第一天。",
      "时间是我们最想要的东西，也是我们浪费得最严重的东西。",
      "像明天就会死一样生活，像永远活着一样学习。",
      "人生苦短，但微笑的时间很充裕。",
      "一天是永恒的缩影。",
      "你虚度の今天，是昨天死去的人苦苦哀求的明天。",
      "此时此刻，你还活着。没有比这更美妙的事了。",
      "死亡不是生命的终点，而是生命的圆满。",
      "生活不只是呼吸，而是行动。",
      "活得最久的人不是岁数最大的人，而是对生活最有感悟的人。",
      "重要的不是你活了多少年，而是这些年里你活得有多精彩。",
      "未来取决于你今天做了什么。",
      "幸福不是留给未来的东西，而是为当下设计的。",
      "你无法改变过去，但你可以从现在开始创造未来。",
      "每一刻都是一个新的开始。",
      "生命的价值不在于长短，而在于如何利用它。",
      "意识到死亡是为了丰富生命。",
      "今天尽你所能。"
    ],
    stoicism: [
      "不要解释你的哲学，去体现它。（爱比克泰德）",
      "我们在想象中受的苦比在现实中多。（塞内卡）",
      "最好的报复就是不要变成像伤害你的人那样。（马可·奥勒留）",
      "人担心的不应该是死亡，而应该是从未开始生活。（马可·奥勒留）",
      "你有权控制自己的思想，而不是外部事件。意识到这一点，你就会找到力量。（马可·奥勒留）",
      "运气是当准备遇到机会时发生的事情。（塞内卡）",
      "勇敢的人是自由的。（塞内卡）",
      "不要再浪费时间争论什么样的人才是好人。去做一个好人。（马可·奥勒留）",
      "如果不正确，就不要做；如果不真实，就不要说。（马可·奥勒留）",
      "困难磨练意志，就像劳动磨练身体一样。（塞内卡）"
    ],
    zen: [
      "日日是好日。",
      "活在当下。",
      "饥来吃饭，困来即眠。",
      "障碍即是道路。",
      "劈柴，挑水。",
      "微笑，呼吸，慢慢来。",
      "做伟大工作的唯一方法是热爱你所做的事情。",
      "不要寻求追随古人的足迹，要寻求他们所寻求的。",
      "禅不是某种兴奋，而是对我们通常日常生活的专注。",
      "一切都在改变；没有什么是永恒的。"
    ],
    entrepreneur: [
      "求知若渴，虚心若愚。（史蒂夫·乔ブス）",
      "你的时间有限，所以不要浪费时间去过别人的生活。（史蒂夫·乔ブス）",
      "失败只是一个重新开始的机会，这一次要更加聪明。（亨利·福特）",
      "庆祝成功固然好，但更重要的是吸取失败的教訓。（比尔·盖茨）",
      "最大の风险就是不冒任何风险。（马克·扎克伯格）",
      "如果你不能飞，那就跑；如果你不能跑，那就走；如果你不能走，那就爬；但无论你做什么，你都必须保持前进。（马丁·路德·金）",
      "成功就是从失败走向失败，而不失去热情。（温斯顿·丘吉尔）",
      "如果你能梦到它，你就能做到它。（华特·迪士尼）",
      "行动是所有成功的基石。（巴勃罗·毕加索）",
      "二十年后，你会为你没做过的事情比为你做过的事情更感到失望。（马克·吐温）"
    ]
  },
  es: {
    mementoMori: [
      "Recuerda que morirás. Ama este momento ahora.",
      "Memento Mori. No olvides la muerte, deja que la vida brille.",
      "Hoy es el primer día del resto de tu vida.",
      "El tiempo es lo que más queremos, pero lo que peor usamos.",
      "Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre.",
      "La vida es corta, pero hay mucho tiempo para sonreír.",
      "Un día es una miniatura de la eternidad.",
      "El hoy que desperdiciaste es el mañana que alguien que murió ayer quería vivir.",
      "En este momento, estás vivo. Nada es más maravilloso que eso.",
      "La muerte no es el fin de la vida; es la culminación de una vida.",
      "Vivir no es solo respirar, sino actuar.",
      "El hombre que más ha vivido no es el que más años ha contado, sino el que más ha sentido la vida.",
      "Al final, no son los años en tu vida los que cuentan. Es la vida en tus años.",
      "El futuro depende de lo que hagas hoy.",
      "La felicidad no es algo que pospones para el futuro; es algo que diseñas para el presente.",
      "No puedes cambiar el pasado, pero puedes crear el futuro a partir de ahora.",
      "Cada momento es un nuevo comienzo.",
      "El valor de la vida no reside en la duración de los días, sino en el uso que hacemos de ellos.",
      "Ser consciente de la muerte es enriquecer la vida.",
      "Haz lo mejor que puedas hoy."
    ],
    stoicism: [
      "No expliques tu filosofía. Encárnala. (Epicteto)",
      "Sufrimos más a menudo en la imaginación que en la realidad. (Séneca)",
      "La mejor venganza es ser diferente de quien realizó la injuria. (Marco Aurelio)",
      "No es la muerte lo que un hombre debe temer, sino que debe temer nunca comenzar a vivir. (Marco Aurelio)",
      "Tienes poder sobre tu mente, no sobre los eventos externos. Date cuenta de esto y encontrarás fuerza. (Marco Aurelio)",
      "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad. (Séneca)",
      "El que es valiente es libre. (Séneca)",
      "No pierdas más tiempo discutiendo qué debe ser un buen hombre. Sé uno. (Marco Aurelio)",
      "Si no es correcto, no lo hagas; si no es verdad, no lo digas. (Marco Aurelio)",
      "Las dificultades fortalecen la mente, como el trabajo hace con el cuerpo. (Séneca)"
    ],
    zen: [
      "Cada día es un buen día.",
      "Estate aquí ahora.",
      "Cuando tengas hambre, come; cuando estés cansado, duerme.",
      "El obstáculo es el camino.",
      "Corta leña, acarrea agua.",
      "Sonríe, respira y ve despacio.",
      "La única forma de hacer un gran trabajo es amar lo que haces.",
      "No busques seguir los pasos de los hombres de antaño; busca lo que ellos buscaron.",
      "El Zen no es una especie de emoción, sino la concentración en nuestra rutina diaria habitual.",
      "Todo está cambiando; nada es permanente."
    ],
    entrepreneur: [
      "Sigue hambriento, sigue alocado. (Steve Jobs)",
      "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de otra persona. (Steve Jobs)",
      "El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de manera más inteligente. (Henry Ford)",
      "Está bien celebrar el éxito, pero es más importante prestar atención a las lecciones del fracaso. (Bill Gates)",
      "El mayor riesgo es no correr ningún riesgo. (Mark Zuckerberg)",
      "Si no puedes volar, corre; si no puedes correr, camina; si no puedes caminar, gatea; pero hagas lo que hagas, tienes que seguir adelante. (Martin Luther King Jr.)",
      "El éxito es caminar de fracaso en fracaso sin pérdida de entusiasmo. (Winston Churchill)",
      "Si puedes soñarlo, puedes hacerlo. (Walt Disney)",
      "La acción es la clave fundamental de todo éxito. (Pablo Picasso)",
      "Dentro de veinte años estarás más decepcionado por las cosas que no hiciste que por las que hiciste. (Mark Twain)"
    ]
  },
  fr: {
    mementoMori: [
      "Souviens-toi que tu vas mourir. Aime ce moment présent.",
      "Memento Mori. N'oublie pas la mort, laisse la vie briller.",
      "Aujourd'hui est le premier jour du reste de ta vie.",
      "Le temps est ce que nous voulons le plus, mais ce que nous utilisons le moins bien.",
      "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre éternellement.",
      "La vie est courte, mais il y a plein de temps pour sourire.",
      "Une journée est une miniature de l'éternité.",
      "Le aujourd'hui que tu as gaspillé est le demain qu'une personne décédée hier voulait vivre.",
      "En ce moment, tu es vivant. Rien n'est plus merveilleux que cela.",
      "La mort n'est pas la fin de la vie ; c'est l'achèvement d'une vie.",
      "Vivre, ce n'est pas seulement respirer, c'est agir.",
      "L'homme qui a le plus vécu n'est pas celui qui a compté le plus d'années, mais celui qui a le plus ressenti la vie.",
      "En fin de compte, ce ne sont pas les années de votre vie qui comptent. C'est la vie dans vos années.",
      "L'avenir dépend de ce que vous faites aujourd'hui.",
      "Le bonheur n'est pas quelque chose que l'on reporte pour l'avenir ; c'est quelque chose que l'on conçoit pour le présent.",
      "Vous ne pouvez pas changer le passé, mais vous pouvez créer l'avenir dès maintenant.",
      "Chaque instant est un nouveau commencement.",
      "La valeur de la vie ne réside pas dans la durée des jours, mas dans l'usage que nous en faisons.",
      "Être conscient de la mort, c'est enrichir la vie.",
      "Faites de votre mieux aujourd'hui."
    ],
    stoicism: [
      "N'explique pas ta philosophie. Incarne-la. (Épictète)",
      "Nous souffrons plus souvent en imagination qu'en réalité. (Sénèque)",
      "La meilleure vengeance est de ne pas ressembler à celui qui a commis l'injure. (Marc Aurèle)",
      "Ce n'est pas la mort qu'un homme devrait craindre, mais il devrait craindre de ne jamais commencer à vivre. (Marc Aurèle)",
      "Vous avez le pouvoir sur votre esprit - pas sur les événements extérieurs. Réalisez cela, et vous trouverez la force. (Marc Aurèle)",
      "La chance est ce qui arrive quand la préparation rencontre l'opportunité. (Sénèque)",
      "Celui qui est courageux est libre. (Sénèque)",
      "Ne perdez plus de temps à discuter de ce que devrait être un homme bon. Soyez-en un. (Marc Aurèle)",
      "Si ce n'est pas juste, ne le fais pas ; si ce n'est pas vrai, ne le dis pas. (Marc Aurèle)",
      "Les difficultés renforcent l'esprit, comme le travail le fait pour le corps. (Sénèque)"
    ],
    zen: [
      "Chaque jour est un bon jour.",
      "Sois ici maintenant.",
      "Quand tu as faim, mange ; quand tu es fatigué, dors.",
      "L'obstacle est le chemin.",
      "Coupe du bois, porte de l'eau.",
      "Souris, respire et va lentement.",
      "La seule façon de faire du bon travail est d'aimer ce que vous faites.",
      "Ne cherchez pas à suivre les traces des hommes d'autrefois ; cherchez ce qu'ils ont cherché.",
      "Le Zen n'est pas une sorte d'excitation, mais la concentration sur notre routine quotidienne habituelle.",
      "Tout change ; rien n'est permanent."
    ],
    entrepreneur: [
      "Restez affamés, restez fous. (Steve Jobs)",
      "Votre temps est limité, alors ne le gaspillez pas à vivre la vie de quelqu'un d'autre. (Steve Jobs)",
      "L'échec est simplement l'occasion de recommencer, cette fois plus intelligemment. (Henry Ford)",
      "C'est bien de fêter le succès, mais il est plus important de tenir compte des leçons de l'échec. (Bill Gates)",
      "Le plus grand risque est de ne prendre aucun risque. (Mark Zuckerberg)",
      "Si vous ne pouvez pas voler, alors courez ; si vous ne pouvez pas courez, alors marchez ; si vous ne pouvez pas marcher, alors rampez ; mais quoi que vous fassiez, vous devez continuer à avancer. (Martin Luther King Jr.)",
      "Le succès, c'est d'aller d'échec en échec sans perdre son enthousiasme. (Winston Churchill)",
      "Si vous pouvez le rêver, vous pouvez le faire. (Walt Disney)",
      "L'action est la clave fondamentale de tout succès. (Pablo Picasso)",
      "Dans vingt ans, vous serez plus déçu par les choses que vous n'avez pas faites que par celles que vous avez faites. (Mark Twain)"
    ]
  }
};
