import { Language } from '../types';

export const QUOTES: Record<Language, string[]> = {
  ja: [
    "終わりを想い、今、この一瞬を愛せ。",
    "メメント・モリ。死を忘れるな、生を輝かせよ。",
    "今日という日は、残りの人生の最初の一日である。",
    "時間は、私たちが最も欲しがるものであるが、最も無駄に使ってしまうものでもある。",
    "明日死ぬかのように生きよ。永遠に生きるかのように学べ。",
    "人生は短い。しかし、微笑む時間はたっぷりある。",
    "一日は一生の短縮版である。",
    "あなたが無駄に過ごした今日は、昨日死んだ誰かが死ぬほど生きたかった明日だ。",
    "今この瞬間、あなたは生きている。それ以上に素晴らしいことはない。",
    "死は人生の終末ではない。生涯の完成である。",
    "生きるとは、呼吸することではない。行動することだ。",
    "最も長生きした人間とは、最も多くの歳月を生きた人間ではなく、最も人生を感じた人間だ。",
    "人生において重要なのは、何年生きたかではない。その歳月の中にどれだけの命があったかだ。",
    "未来は、今、あなたが何をするかにかかっている。",
    "幸福は、明日手に入れるものではない。今日、この瞬間に作り出すものだ。",
    "過去は変えられないが、未来は今から作ることができる。",
    "一瞬一瞬が、新しい始まりだ。",
    "人生の価値は、その長さではなく、その使い方で決まる。",
    "死を意識することは、生を豊かにすることだ。",
    "今日、あなたができる最善を尽くせ。"
  ],
  en: [
    "Remember that you must die. Love this moment now.",
    "Memento Mori. Do not forget death, let life shine.",
    "Today is the first day of the rest of your life.",
    "Time is what we want most, but what we use worst.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "Life is short, but there is plenty of time to smile.",
    "A day is a miniature of eternity.",
    "The today you wasted is the tomorrow someone who died yesterday wanted to live.",
    "At this moment, you are alive. Nothing is more wonderful than that.",
    "Death is not the end of life; it is the completion of a lifetime.",
    "To live is not just to breathe, but to act.",
    "The man who has lived the most is not he who has counted the most years but he who has most felt life.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "The future depends on what you do today.",
    "Happiness is not something you postpone for the future; it is something you design for the present.",
    "You cannot change the past, but you can create the future starting now.",
    "Every moment is a fresh beginning.",
    "The value of life lies not in the length of days, but in the use we make of them.",
    "Being aware of death is to enrich life.",
    "Do your best today."
  ],
  zh: [
    "记住你终将逝去，爱在当下。",
    "记住死亡，让生命闪耀。",
    "今天是你余生的第一天。",
    "时间是我们最想要的东西，也是我们浪费得最严重的东西。",
    "像明天就会死一样生活，像永远活着一样学习。",
    "人生苦短，但微笑的时间很充裕。",
    "一天是永恒的缩影。",
    "你虚度的今天，是昨天死去的人苦苦哀求的明天。",
    "此时此刻，你还活着。没有比这更美妙的事了。",
    "死亡不是生命的终点，而是生命的圆满。",
    "生活不只是呼吸，而是行动。",
    "活得最久的人不是岁数最大的人，而是对生活最有感悟的人。",
    "重要的不是你活了多少年，而是这些年里你活得有多精彩。",
    "未来取决于你今天做了什么。",
    "幸福不是留给未来的东西，而是为当下设计的。",
    "你无法改变过去，但你可以从现在开始创造未来。",
    "每一刻都是一个新的开始。",
    "生命的价值不在于长短，而在于如何利用它。",
    "意识到死亡是为了丰富生命。",
    "今天尽你所能。"
  ],
  es: [
    "Recuerda que morirás. Ama este momento ahora.",
    "Memento Mori. No olvides la muerte, deja que la vida brille.",
    "Hoy es el primer día del resto de tu vida.",
    "El tiempo es lo que más queremos, pero lo que peor usamos.",
    "Vive como si fueras a morir mañana. Aprende como si fueras a vivir siempre.",
    "La vida es corta, pero hay mucho tiempo para sonreír.",
    "Un día es una miniatura de la eternidad.",
    "El hoy que desperdiciaste es el mañana que alguien que murió ayer quería vivir.",
    "En este momento, estás vivo. Nada es más maravilloso que eso.",
    "La muerte no es el fin de la vida; es la culminación de una vida.",
    "Vivir no es solo respirar, sino actuar.",
    "El hombre que más ha vivido no es el que más años ha contado, sino el que más ha sentido la vida.",
    "Al final, no son los años en tu vida los que cuentan. Es la vida en tus años.",
    "El futuro depende de lo que hagas hoy.",
    "La felicidad no es algo que pospones para el futuro; es algo que diseñas para el presente.",
    "No puedes cambiar el pasado, pero puedes crear el futuro a partir de ahora.",
    "Cada momento es un nuevo comienzo.",
    "El valor de la vida no reside en la duración de los días, sino en el uso que hacemos de ellos.",
    "Ser consciente de la muerte es enriquecer la vida.",
    "Haz lo mejor que puedas hoy."
  ],
  fr: [
    "Souviens-toi que tu vas mourir. Aime ce moment présent.",
    "Memento Mori. N'oublie pas la mort, laisse la vie briller.",
    "Aujourd'hui est le premier jour du reste de ta vie.",
    "Le temps est ce que nous voulons le plus, mais ce que nous utilisons le moins bien.",
    "Vis comme si tu devais mourir demain. Apprends comme si tu devais vivre éternellement.",
    "La vie est courte, mais il y a plein de temps pour sourire.",
    "Une journée est une miniature de l'éternité.",
    "Le aujourd'hui que tu as gaspillé est le demain qu'une personne décédée hier voulait vivre.",
    "En ce moment, tu es vivant. Rien n'est plus merveilleux que cela.",
    "La mort n'est pas la fin de la vie ; c'est l'achèvement d'une vie.",
    "Vivre, ce n'est pas seulement respirer, c'est agir.",
    "L'homme qui a le plus vécu n'est pas celui qui a compté le plus d'années, mais celui qui a le plus ressenti la vie.",
    "En fin de compte, ce ne sont pas les années de votre vie qui comptent. C'est la vie dans vos années.",
    "L'avenir dépend de ce que vous faites aujourd'hui.",
    "Le bonheur n'est pas quelque chose que l'on reporte pour l'avenir ; c'est quelque chose que l'on conçoit pour le présent.",
    "Vous ne pouvez pas changer le passé, mais vous pouvez créer l'avenir dès maintenant.",
    "Chaque instant est un nouveau commencement.",
    "La valeur de la vie ne réside pas dans la durée des jours, mais dans l'usage que nous en faisons.",
    "Être conscient de la mort, c'est enrichir la vie.",
    "Faites de votre mieux aujourd'hui."
  ]
};
