export const COUNTRY_CODES: Record<string, string> = {
  "Japan": "JP",
  "Singapore": "SG",
  "South Korea": "KR",
  "Switzerland": "CH",
  "Australia": "AU",
  "Spain": "ES",
  "Norway": "NO",
  "Iceland": "IS",
  "Israel": "IL",
  "Italy": "IT",
  "Sweden": "SE",
  "France": "FR",
  "Canada": "CA",
  "Luxembourg": "LU",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Ireland": "IE",
  "Austria": "AT",
  "Finland": "FI",
  "Germany": "DE",
  "Belgium": "BE",
  "UK": "GB",
  "Greece": "GR",
  "Portugal": "PT",
  "Slovenia": "SI",
  "Denmark": "DK",
  "Cyprus": "CY",
  "USA": "US",
  "China": "CN",
  "Brazil": "BR",
  "Russia": "RU",
  "India": "IN",
  "Global": "UN"
};
